### PR TITLE
Add setup script

### PR DESCRIPTION
**Pull request by EhWhoAmI**
The script checks if the setup is in the right directory.
Also, fixed grammar.

### CODE REVIEW

**Comment by RyanMaugin** [comment]
Can you implement the equivalent of what you did in the SH script to the setup.py script within the `setup` method as having 2 setup scripts is redundant.

**Comment by EhWhoAmI** [comment]
I'll try. Wont be too hard.

**Comment by EhWhoAmI** [comment]
Fixed it, i think. Will test it soon.

**Comment by EhWhoAmI** [comment]
I think I just made it work for windows. I managed to create the installer. Also, can you change the name of parser.py to tnparse.py, so that the computer will not get messed up with the `Parser` class that is inbuilt (Commit 0d1173e). This is for everyone to use, so if you are ok, I was not, and you want everyone to use it, right?

**Comment by EhWhoAmI** [comment]
Do you know how to resolve merge conflicts?

**Comment by EhWhoAmI** [comment]
HELLO???? I AM WAITING...

**Comment by EhWhoAmI** [comment]
Closed because submitting a non conflicted version.

**Pull request closed without merging**
